### ISSUE TITLE
Package listing on NuGet

### ISSUE THREAD

**Issue by alexeyzimarev** [i4004/RestSharp.Newtonsoft.Json.Extensions#7]
Hey,

Thank you for supporting RestSharp :) I'd like, however, to ask you to remove (unlist) your package since RestSharp supports .NET Core and also has the NewtonsoftJson serializer as a dedicated package (https://www.nuget.org/packages/RestSharp.Serializers.NewtonsoftJson) for a while now so we don't confuse users.

Thanks and regards,
Alexey Zimarev
Maintainer of RestSharp

**Comment by i4004** [comment]
Hi! Done. I made a package deprecation, so there will be a specific messages for users to use your package, is this enough?
If there is no more questions, then I am about to archive this repository.

**Comment by alexeyzimarev** [comment]
Thanks! Really appreciate it.
